TRUNCATE TABLE public.active_project RESTART IDENTITY CASCADE;

TRUNCATE TABLE public.admin_user RESTART IDENTITY CASCADE;

TRUNCATE TABLE public.archive_project RESTART IDENTITY CASCADE;

TRUNCATE TABLE public.project_used RESTART IDENTITY CASCADE;

TRUNCATE TABLE public.requested_project RESTART IDENTITY CASCADE;

TRUNCATE TABLE public.requestor_user RESTART IDENTITY CASCADE;

TRUNCATE TABLE public.segment RESTART IDENTITY CASCADE;
